### ISSUE TITLE
can't load avalonia project

### ISSUE THREAD

**Issue by markjbrown** [peppial/LiteCosmosExplorer#23]
this error prevents the solution from loading the avalonia project.

\LiteCosmosExplorer\CosmosExplorer.Avalonia\CosmosExplorer.Avalonia.csproj : error  : Duplicated folder item found in the project: "Assets\favicon.ico".

**Comment by peppial** [comment]
@markbrown 

Thank you! This is fixed, can you please pull and try again.

**Comment by markjbrown** [comment]
Thanks! Project loads.
